openapi: 3.0.1
info:
  title: Now Playing API
  description: Now Playing API.
  contact:
    email: jeremiejost@gmail.com
  version: 0.1.0
servers:
- url: /api
tags:
- name: stations
  description: Find radio stations and what they're playing
  externalDocs:
    description: Find out more
    url: https://github.com/jjst/now-playing
paths:
  /search:
    get:
      tags:
      - stations
      summary: Find a station by name
      operationId: search
      parameters:
      - name: query
        in: query
        description: Search query
        required: true
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResult'
        400:
          description: Invalid query
          content: {}
      x-openapi-router-controller: api.controllers.stations_controller
  /stations:
    get:
      tags:
      - stations
      summary: List all stations
      description: Gets all radio stations
      operationId: get_stations
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RadioStationList'
      x-openapi-router-controller: api.controllers.stations_controller
  /stations/{namespace}:
    get:
      tags:
      - stations
      summary: List all stations in a namespace
      description: Gets all radio stations in a namespace
      operationId: get_stations_by_country_code
      parameters:
      - name: namespace
        in: path
        description: Country code of a station
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RadioStationList'
        404:
          description: Station not found
          content: {}
      x-openapi-router-controller: api.controllers.stations_controller
  /stations/{namespace}/{slug}:
    get:
      tags:
      - stations
      summary: Get radio station information
      description: Returns a radio station
      operationId: get_station_by_country_code_and_station_id
      parameters:
      - name: namespace
        in: path
        description: Namespace of a station
        required: true
        schema:
          type: string
      - name: slug
        in: path
        description: slug (short human-readable id) of a station
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RadioStation'
        404:
          description: Station not found
          content: {}
      x-openapi-router-controller: api.controllers.stations_controller
  /stations/{namespace}/{slug}/now-playing:
    get:
      tags:
      - stations
      summary: Get now playing information for a given station
      description: Returns what a radio station is currently playing. This will return
        a song or programme title.
      operationId: get_now_playing_by_country_code_and_station_id
      parameters:
      - name: namespace
        in: path
        description: Country code of a station
        required: true
        schema:
          type: string
      - name: slug
        in: path
        description: ID of a station
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NowPlaying'
        404:
          description: now-playing information for this station is not available
          content: {}
      x-openapi-router-controller: api.controllers.stations_controller
components:
  schemas:
    SearchResult:
      required:
      - items
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/RadioStation'
    RadioStationList:
      required:
      - items
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/RadioStation'
    RadioStation:
      required:
      - id
      - name
      - namespace
      - slug
      type: object
      properties:
        id:
          type: string
        namespace:
          type: string
        slug:
          type: string
        name:
          type: string
        favicon:
          type: string
          format: uri
        country_code:
          type: string
        streams:
          type: array
          items:
            $ref: '#/components/schemas/Stream'
      example:
        namespace: fr
        slug: radiomeuh
        id: fr/radiomeuh
        country_code: fr
        name: Radio Meuh
        streams:
        - url: http://radiomeuh.ice.infomaniak.ch/radiomeuh-128.mp3
          bitrate_kbps: 128
    Stream:
      required:
      - url
      type: object
      properties:
        url:
          type: string
          format: url
        quality:
          type: string
        bitrate_kbps:
          type: integer
          format: int32
      example:
        url: http://radiomeuh.ice.infomaniak.ch/radiomeuh-128.mp3
        bitrate_kbps: 128
    NowPlaying:
      type: object
      properties:
        title:
          type: string
        type:
          type: string
          enum:
          - song
          - programme
        metadata:
          type: object
          properties: {}
      example:
        title: Europe - The Final Countdown
        type: song
