openapi: 3.0.1
info:
  title: Now Playing API
  description: Now Playing API.
  contact:
    email: jeremiejost@gmail.com
  version: 0.1.0
servers:
- url: /api
tags:
- name: stations
  description: Find radio stations and what they're playing
  externalDocs:
    description: Find out more
    url: https://github.com/jjst/now-playing
paths:
  /search:
    get:
      tags:
      - stations
      summary: Find a station by name
      operationId: search
      parameters:
      - name: query
        in: query
        description: Search query
        required: true
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResult'
        400:
          description: Invalid query
          content: {}
      x-openapi-router-controller: api.controllers.stations_controller
  /stations:
    get:
      tags:
      - stations
      summary: List all stations
      description: Gets all radio stations
      operationId: get_stations
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RadioStationList'
      x-openapi-router-controller: api.controllers.stations_controller
  /stations/{namespace}:
    get:
      tags:
      - stations
      summary: List all stations in a namespace
      description: Gets all radio stations in a namespace
      operationId: get_stations_by_country_code
      parameters:
      - name: namespace
        in: path
        description: Country code of a station
        required: true
        schema:
          type: string
          example: fr
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RadioStationList'
        404:
          description: Station not found
          content: {}
      x-openapi-router-controller: api.controllers.stations_controller
  /stations/{namespace}/{slug}:
    get:
      tags:
      - stations
      summary: Get radio station information
      description: Returns a radio station
      operationId: get_station_by_country_code_and_station_id
      parameters:
      - name: namespace
        in: path
        description: Namespace of a station
        required: true
        schema:
          type: string
          example: fr
      - name: slug
        in: path
        description: A short, human-readable identifier for a radio station, unique in a given namespace
        required: true
        schema:
          type: string
          example: radiomeuh
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RadioStation'
        404:
          description: Station not found
          content: {}
      x-openapi-router-controller: api.controllers.stations_controller
  /stations/{namespace}/{slug}/now-playing:
    get:
      tags:
      - stations
      summary: Get now playing information for a given station
      description: Returns what a radio station is currently playing. This will return
        a song or programme title.
      operationId: get_now_playing_by_country_code_and_station_id
      parameters:
      - name: namespace
        in: path
        description: Namespace of a station
        required: true
        schema:
          type: string
          example: fr
      - name: slug
        in: path
        description: A short, human-readable identifier for a radio station, unique in a given namespace
        required: true
        schema:
          type: string
          example: radiomeuh
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NowPlayingItemList'
        404:
          description: now-playing information for this station is not available
          content: {}
      x-openapi-router-controller: api.controllers.stations_controller
components:
  schemas:
    SearchResult:
      required:
      - items
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/RadioStation'
    RadioStationList:
      required:
      - items
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/RadioStation'
    RadioStation:
      required:
      - id
      - name
      - namespace
      - slug
      type: object
      properties:
        id:
          type: string
        namespace:
          type: string
        slug:
          type: string
        name:
          type: string
        favicon:
          type: string
          format: uri
        country_code:
          type: string
        streams:
          type: array
          items:
            $ref: '#/components/schemas/Stream'
      example:
        namespace: fr
        slug: radiomeuh
        id: fr/radiomeuh
        country_code: fr
        name: Radio Meuh
        streams:
        - url: http://radiomeuh.ice.infomaniak.ch/radiomeuh-128.mp3
          bitrate_kbps: 128
    Stream:
      required:
      - url
      type: object
      properties:
        url:
          type: string
          format: url
        codec:
          type: string
        quality:
          type: string
        bitrate_kbps:
          type: integer
          format: int32
      example:
        url: http://radiomeuh.ice.infomaniak.ch/radiomeuh-128.mp3
        codec: mp3
        bitrate_kbps: 128
    NowPlayingItemList:
      required:
      - items
      type: object
      properties:
        items:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/Song'
              - $ref: '#/components/schemas/Programme'
    NowPlayingItem:
      type: object
      required:
        - type
        - text
      properties:
        text:
          type: string
        type:
          type: string
          enum:
          - song
          - programme
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
      example:
        text: Europe - The Final Countdown
        type: song
        start_time: 2017-07-21T17:32:28Z
        end_time: 2017-07-21T17:37:37Z
    Song:
      allOf:
        - $ref: '#/components/schemas/NowPlayingItem'
        - type: object
          required:
            - artist
            - title
          properties:
            artist:
              type: string
            title:
              type: string
            album:
              type: string
            cover_art:
              type: string
          example:
            text: Europe - The Final Countdown
            type: song
            artist: Europe
            title: The Final Countdown
            start_time: 2017-07-21T17:32:28Z
            end_time: 2017-07-21T17:37:37Z
    Programme:
      allOf:
        - $ref: '#/components/schemas/NowPlayingItem'
        - type: object
          required:
            - name
          properties:
            name:
              type: string
            episode_title:
              type: string
          example:
            text: SOUS LE SOLEIL DE PLATON - Une leçon de cinéma, avec le réalisateur Michel Hazanavicius
            type: programme
            name: SOUS LE SOLEIL DE PLATON
            episode_title: Une leçon de cinéma, avec le réalisateur Michel Hazanavicius
            start_time: 2021-07-15T10:06:28Z
            end_time: 2021-07-15T11:04:07Z
