---
swagger: "2.0"
info:
  description: "Now Playing API."
  version: "0.1.0"
  title: "Now Playing API"
  contact:
    email: "jeremiejost@gmail.com"
basePath: "/api"
tags:
- name: "stations"
  description: "Find radio stations and what they're playing"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/jjst/now-playing"
schemes:
- "https"
- "http"
paths:
  /search:
    get:
      tags:
      - "stations"
      summary: "Find a station by name"
      operationId: "search"
      produces:
      - "application/json"
      parameters:
      - name: "query"
        in: "query"
        description: "Search query"
        required: true
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/SearchResult"
        "400":
          description: "Invalid query"
      x-swagger-router-controller: "api.controllers.stations_controller"
  /stations:
    get:
      tags:
      - "stations"
      summary: "List all stations"
      description: "Gets all radio stations"
      operationId: "get_stations"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/RadioStationList"
      x-swagger-router-controller: "api.controllers.stations_controller"
  /stations/{namespace}:
    get:
      tags:
      - "stations"
      summary: "List all stations in a namespace"
      description: "Gets all radio stations in a namespace"
      operationId: "get_stations_by_country_code"
      produces:
      - "application/json"
      parameters:
      - name: "namespace"
        in: "path"
        description: "Country code of a station"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/RadioStationList"
        "404":
          description: "Station not found"
      x-swagger-router-controller: "api.controllers.stations_controller"
  /stations/{namespace}/{slug}:
    get:
      tags:
      - "stations"
      summary: "Get radio station information"
      description: "Returns a radio station"
      operationId: "get_station_by_country_code_and_station_id"
      produces:
      - "application/json"
      parameters:
      - name: "namespace"
        in: "path"
        description: "Namespace of a station"
        required: true
        type: "string"
      - name: "slug"
        in: "path"
        description: "slug (short human-readable id) of a station"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/RadioStation"
        "404":
          description: "Station not found"
      x-swagger-router-controller: "api.controllers.stations_controller"
  /stations/{namespace}/{slug}/now-playing:
    get:
      tags:
      - "stations"
      summary: "Get now playing information for a given station"
      description: "Returns what a radio station is currently playing. This will return a song or programme title."
      operationId: "get_now_playing_by_country_code_and_station_id"
      produces:
      - "application/json"
      parameters:
      - name: "namespace"
        in: "path"
        description: "Country code of a station"
        required: true
        type: "string"
      - name: "slug"
        in: "path"
        description: "ID of a station"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/NowPlaying"
        "404":
          description: "now-playing information for this station is not available"
      x-swagger-router-controller: "api.controllers.stations_controller"
definitions:
  SearchResult:
    type: "object"
    required:
    - "items"
    properties:
      items:
        type: "array"
        items:
          $ref: "#/definitions/RadioStation"
  RadioStationList:
    type: "object"
    required:
    - "items"
    properties:
      items:
        type: "array"
        items:
          $ref: "#/definitions/RadioStation"
  RadioStation:
    type: "object"
    required:
    - "namespace"
    - "slug"
    - "id"
    - "name"
    properties:
      id:
        type: "string"
      namespace:
        type: "string"
      slug:
        type: "string"
      name:
        type: "string"
      favicon:
        type: "string"
        format: uri
      country_code:
        type: "string"
      streams:
        type: array
        items:
          $ref: "#/definitions/Stream"
    example:
      namespace: "fr"
      slug: "radiomeuh"
      id: "fr/radiomeuh"
      country_code: "fr"
      name: "Radio Meuh"
      streams:
        - url: "http://radiomeuh.ice.infomaniak.ch/radiomeuh-128.mp3"
          bitrate_kbps: 128
  Stream:
    type: "object"
    required:
    - "url"
    properties:
      url:
        type: "string"
        format: url
      quality:
        type: "string"
      bitrate_kbps:
        type: integer
        format: int32
    example:
      url: "http://radiomeuh.ice.infomaniak.ch/radiomeuh-128.mp3"
      bitrate_kbps: 128
  NowPlaying:
    type: "object"
    properties:
      title:
        type: "string"
      type:
        type: "string"
        enum:
          - song
          - programme
      metadata:
        type: object
    example:
      title: "Europe - The Final Countdown"
      type: "song"
