s3:
  enabled: False
  endpoint_url: https://s3.eu-central-1.wasabisys.com
  bucket_name: now-playing-aggregated-data
redis:
  url: redis://localhost:6379/0
  args:
    socket_timeout: 5
    socket_connect_timeout: 5
response_cache:
  default_ttl_seconds: 10
  default_ttl_seconds_if_changed: 120
requests:
  default_timeout_seconds: 10
  cache_ttl_seconds: 10
