name: now-playing
region: fra
services:
- name: now-playing
  envs:
  - key: APPLICATION_VERSION
    scope: RUN_TIME
    value: $APPLICATION_VERSION
  - key: LS_SERVICE_NAME
    scope: RUN_TIME
    value: now-playing
  - key: LS_SERVICE_VERSION
    scope: RUN_TIME
    value: $APPLICATION_VERSION
  - key: LS_ACCESS_TOKEN
    scope: RUN_TIME
    type: SECRET
    value: EV[1:N/Eru6BnFSEdGli37J1i/qIv/KryiscU:zmEt1jUTliqofKOWvH5SML3Fw+GkA+gLGFESsJ0WBLTdr79e6a8xxtL2icId7Im5oevkHAgQQfIVP7DDXwYgTkadF5KUXZEOOUdSe14+jMJyrHkrRSGJfmtwNg5d6pmm+qMPOrlZmlt2uAfcK9lfn0ALEDeTNfVf]
  - key: AWS_ACCESS_KEY_ID
    scope: RUN_TIME
    type: SECRET
    value: EV[1:h+kn+SxevlSrPEd6QMq7pP9ErPQKA9EE:p2t1PXXLxW8/IYRGrLhkXVDcHZaqI+KWZoy9qIf0FjalPquI]
  - key: AWS_SECRET_ACCESS_KEY
    scope: RUN_TIME
    type: SECRET
    value: EV[1:I7bGtB42t5k+gXQR+rWrBU6Eap7KBunx:WsHMtddtdvdFOvoCaPXsIxuBAhB6LMQNB4ZChfy9/XAT9+YWVerPaPjV2LFVxN9A5O6jxSebw6g=]
  - key: redis__url
    scope: RUN_TIME
    value: redis://redis:6379/0
  - key: s3__enabled
    scope: RUN_TIME
    value: "true"
  image:
    registry: jjst
    registry_type: DOCKER_HUB
    repository: now-playing
    tag: $APPLICATION_VERSION
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  source_dir: /
  health_check:
    initial_delay_seconds: 5
    period_seconds: 5
    timeout_seconds: 5
    success_threshold: 3
    failure_threshold: 3
    http_path: /api/stations
- name: redis
  image:
    registry_type: DOCKER_HUB
    registry: jjst
    repository: redis
    tag: $APPLICATION_VERSION
  instance_size_slug: basic-xxs
  internal_ports:
    - 6379
