name: now-playing
region: fra
services:
- dockerfile_path: Dockerfile
  envs:
  - key: APPLICATION_VERSION
    scope: RUN_TIME
    value: $APPLICATION_VERSION
  - key: LS_SERVICE_NAME
    scope: RUN_TIME
    value: now-playing
  - key: LS_SERVICE_VERSION
    scope: RUN_TIME
    value: $APPLICATION_VERSION
  - key: LS_ACCESS_TOKEN
    scope: RUN_TIME
    type: SECRET
    value: EV[1:N/Eru6BnFSEdGli37J1i/qIv/KryiscU:zmEt1jUTliqofKOWvH5SML3Fw+GkA+gLGFESsJ0WBLTdr79e6a8xxtL2icId7Im5oevkHAgQQfIVP7DDXwYgTkadF5KUXZEOOUdSe14+jMJyrHkrRSGJfmtwNg5d6pmm+qMPOrlZmlt2uAfcK9lfn0ALEDeTNfVf]
  image:
    registry: jjst
    registry_type: DOCKER_HUB
    repository: now-playing
    tag: latest
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: now-playing
  routes:
  - path: /
  source_dir: /
  health_check:
    initial_delay_seconds: 5
    period_seconds: 5
    timeout_seconds: 5
    success_threshold: 3
    failure_threshold: 3
    http_path: /api/stations/fr/
