aggregators:
  - module: radio_meuh
    stations: 
      - fr/radiomeuh
  - module: fip
    stations: 
      - fr/fip
      - fr/fip-rock
      - fr/fip-pop
      - fr/fip-groove
      - fr/fip-reggae
      - fr/fip-electro
      - fr/fip-nouveautes
      - fr/fip-monde
  - module: france_inter
    stations: 
      - fr/france-inter
      - fr/france-bleu-alsace
