# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
from api import util


class NowPlaying(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, title: str=None, type: str=None, metadata: object=None):  # noqa: E501
        """NowPlaying - a model defined in Swagger

        :param title: The title of this NowPlaying.  # noqa: E501
        :type title: str
        :param type: The type of this NowPlaying.  # noqa: E501
        :type type: str
        :param metadata: The metadata of this NowPlaying.  # noqa: E501
        :type metadata: object
        """
        self.swagger_types = {
            'title': str,
            'type': str,
            'metadata': object
        }

        self.attribute_map = {
            'title': 'title',
            'type': 'type',
            'metadata': 'metadata'
        }

        self._title = title
        self._type = type
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'NowPlaying':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NowPlaying of this NowPlaying.  # noqa: E501
        :rtype: NowPlaying
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this NowPlaying.


        :return: The title of this NowPlaying.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this NowPlaying.


        :param title: The title of this NowPlaying.
        :type title: str
        """

        self._title = title

    @property
    def type(self) -> str:
        """Gets the type of this NowPlaying.


        :return: The type of this NowPlaying.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this NowPlaying.


        :param type: The type of this NowPlaying.
        :type type: str
        """

        self._type = type

    @property
    def metadata(self) -> object:
        """Gets the metadata of this NowPlaying.


        :return: The metadata of this NowPlaying.
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: object):
        """Sets the metadata of this NowPlaying.


        :param metadata: The metadata of this NowPlaying.
        :type metadata: object
        """

        self._metadata = metadata
