name: CI

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest tox
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test
        run: |
          tox
  gen-app-version:
    name: Generate app version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: gen-version
        run: |
          app_version=$(./gen-app-version.sh)
          echo "App version: $app_version"
          echo "::set-output name=version::$app_version"
    outputs:
      app-version: ${{ steps.gen-version.outputs.version }}
  build-image:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: gen-app-version
    env:
      IMAGE_NAME: jjst/now-playing:${{ needs.gen-app-version.outputs.app-version }}
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2
      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        run: |
          docker build -t $IMAGE_NAME .
      - name: Test image runs
        run: |
          docker run --rm --name now-playing -d -p 8080:8080 $IMAGE_NAME
          docker top now-playing
      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker push $IMAGE_NAME
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [gen-app-version, build-image]
    steps:
      - uses: actions/checkout@v2
      - name: Generate app spec from template
        env:
          APPLICATION_VERSION: ${{ needs.gen-app-version.outputs.app-version }}
        run: |
          envsubst < ./deploy/app.template.yaml > ./deploy/app.yaml
          echo "Generated deploy file:"
          echo "----------------------"
          cat $DEPLOY_FILE_PATH
      - name: Deploy app
        uses: jjst/action-digitalocean-deploy-app@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

