name: Health check

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  health-check:
    runs-on: ubuntu-latest
    name: Run health check
    env:
      APP_HOSTNAME: https://now-playing-42nq5.ondigitalocean.app
      NAMESPACE: fr
    steps:
      - name: Setup
        run: |
          sudo apt install httpie jq
      - name: Health check
        run: |
          stations=$(http $APP_HOSTNAME/api/stations/$NAMESPACE/ | jq -r '.items | .[] | .id')
          echo $stations
          for id in $stations; do
            http $APP_HOSTNAME/api/stations/$NAMESPACE/$id/now-playing
          done

