name: Health check

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
  push:
    paths:
      - '.github/workflows/healthcheck.yaml'
      - 'deploy/health-check.sh'

jobs:
  health-check:
    runs-on: ubuntu-latest
    name: Run health check
    env:
      APP_HOSTNAME: https://now-playing-42nq5.ondigitalocean.app
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          sudo apt install httpie jq
      - name: Health check
        run: |
          ./deploy/health-check.sh

